version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 99
    cooldown:
      default-days: 7
    ignore:
      # https://github.com/mozilla/addons-linter/issues/6222
      - dependency-name: eslint
        versions:
          - ">= 10"
      # https://github.com/mozilla/addons-linter/issues/6223
      - dependency-name: yargs
        versions:
          - ">= 18"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    groups:
      ssdlc-actions:
        patterns:
          - "mozilla/ssdlc-actions/*"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 99
