## Force 64bit platform and nodejs, the addons-linter has dependencies which
## do not provide a pre-compiled 32bit version of their nodejs binary module.
platform: x64
install:
  - ps: Install-Product node $env:nodejs_version x64
  - set CI=true
  - set PATH=%APPDATA%\npm;%PATH%
  - yarn install

matrix:
  fast_finish: true

build: off
shallow_clone: true

# Keep the following configs in sync with .travis.yml
environment:
  matrix:
    - nodejs_version: '8'
    - nodejs_version: '10'

test_script:
  - node --version
  - npm --version
  - yarn --version
  ### This npm script will execute the same tests executed by test-ci
  ### but it skips coveralls (which is not currently recognized when
  ### used from appveyor).
  - yarn run test-coverage-once
  ### Building the dist file is needed by the linting step.
  - yarn run build
  - yarn run lint
  # run integration tests using an addons-linter binary in a production-like environment
  - yarn run test-integration:production
