// This file is generated by the schema import script.

import accounts from './accounts.json';
import mailingLists from './addressBook.json';
import browserAction from './browserAction.json';
import chrome_settings_overrides from './chrome_settings_overrides.json';
import cloudFile from './cloudFile.json';
import compose from './compose.json';
import composeAction from './composeAction.json';
import composeScripts from './composeScripts.json';
import folders from './folders.json';
import mailTabs from './mailTabs.json';
import menus from './menus.json';
import messageDisplay from './messageDisplay.json';
import messageDisplayAction from './messageDisplayAction.json';
import messages from './messages.json';
import tabs from './tabs.json';
import windows from './windows.json';
import contextMenus from './context_menus.json';
export default [
  accounts,
  mailingLists,
  browserAction,
  chrome_settings_overrides,
  cloudFile,
  compose,
  composeAction,
  composeScripts,
  folders,
  mailTabs,
  menus,
  messageDisplay,
  messageDisplayAction,
  messages,
  tabs,
  windows,
  contextMenus,
];
