#!/usr/bin/env node
/* eslint-disable global-require */

const fs = require('fs');
const path = require('path');

const { globSync } = require('glob');
const po2json = require('po2json');
const shelljs = require('shelljs');
const toSource = require('tosource');

const config = require('../config');

const localeDir = path.join(__dirname, '../locale');
const poFiles = globSync(`${localeDir}/**/messages.po`);
const dest = path.join(__dirname, '../dist/locale/');

poFiles.forEach((pofile) => {
  const dir = path.dirname(pofile);
  const subdir = path.dirname(dir);
  const locale = path.basename(subdir);
  const localeOutputFilePath = path.join(dest, locale, `messages.js`);
  shelljs.mkdir('-p', path.join(dest, locale));

  const json = po2json.parseFileSync(pofile, {
    stringify: true,
    pretty: true,
    format: 'jed',
    fuzzy: config.po2jsonFuzzyOutput,
  });
  const localeObject = JSON.parse(json);

  fs.writeFileSync(
    localeOutputFilePath,
    `module.exports = ${toSource(localeObject)}`
  );
});
