#!/usr/bin/env bash

# Build addons-linter
npm install
npm run build

LINTER_PATH=`pwd`

# Fetch web-ext
git clone https://github.com/mozilla/web-ext
cd web-ext

# install web-ext's dependencies, then link the addons-linter
# dependency from the local addons-linter repo clone.
npm install
mv node_modules/addons-linter node_modules/addons-linter.npm
ln -s $LINTER_PATH node_modules/addons-linter

# Run web-ext functional tests
MOCHA_TIMEOUT=60000 npm run test-functional
status_code=$?

# Cleanup
cd ..
rm -rf web-ext

exit $status_code
